name: Create and Publish

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed  
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Pack
        run: dotnet pack --configuration Release --no-restore
      - name: Publish
        run: dotnet nuget push **/*.nupkg -Source 'https://nuget.pkg.github.com/EinQuadrat/index.json' -ApiKey ${{ secrets.GITHUB_TOKEN }}
        